version: "3"
services:
    frontend:
        build: ./frontend
        ports:
            - "3000:3000"

    backend:
        build: ./backend
        ports:
            - "3001:3001"
        environment:
            - DATABASE_URL=mysql://user:password@db:3306/mydatabase

    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - "80:80"
        depends_on:
            - frontend
            - backend

    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: mydatabase
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
