version: "3"
services:
    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        depends_on:
            - backend
        environment:
            - NEXT_PUBLIC_API_URL=http://localhost:3001

    backend:
        build: ./backend
        ports:
            - "3001:3001"
        depends_on:
            - db
        environment:
            - DATABASE_URL=mysql://user:password@db:3306/mydatabase

    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: mydatabase
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
